import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300"],
  variable: "--font-inter",
});

export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.variable}>
        <main>{children}</main>
      </body>
    </html>
  );
}
