import { Poppins } from "next/font/google";
import style from "./Style/login.module.scss";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${poppins.variable} ${style.login}`}>
        <main className={style.loginContainer}>{children}</main>
      </body>
    </html>
  );
}
